---
title: "About"
output: html_document
---


## OneMap software

The OneMap software was first developed by Gabriel Margarido, Marcelo Mollinari and Antonio Augusto Fraco Garcia and published in 2007(ref). It was one of the first softwares able to build genetic maps for outcrossing species. For this it makes use of two-points estimations for each combinations of markers and a HMM approach which combine informations from every marker in the linkage group to estimate the genetic distances. But, the software was first developted to deal with few and informative genetic markers, as microssatelites, with the modern high-throughput markers OneMap now have to deal with thousands of markers, with low-informativeness and a lot of genotype errors. Without a adaptation of the software it produces inflated maps and takes a lot of time to run.

## OneMap workflows

OneMap workflow uses [WDL]() language and [cromwell]() from [Broad Institute]() to offer user friendly and optimazed memory, CPU and time workflows to build linkage maps with OneMap. There are two main workflows called SimulatedReads and EmpiricalReads. The first performs population and RADseq fastq files simulations for a chromosome, SNP and genoytpe calling with five different software and genetic map building with OneMap and Gusmap. EmpiricalReads receives fastq files from empirical data and also performs the SNP and genotype calling and map building.

The main workflows are composed by sub-workflows that can also be useful for users, they are located at `tasks` folder. The sub-workflows are composed by tasks that can be find at the end of each `.wdl` file and at `utils.wdl` and `utilsR.wdl`.

[Docker]() images were built to each one of the tasks, then users need only to download the most recent version of cromwell, install its requirements and docker. If running without sudo permission users can use [singularity]() instead of directly docker. See `.configurations` directory and its [instructions]() to use singulatiry.

The WDL and cromwell system is also made to be easily expansible. Users can change arguments or implement other software into the analysis.

The main goals of OneMap workflows are test software capabilities in ideal scenarios (SimulatedReads) and in empirical data (EmpiricalReads). SimulatedReads also gives a safe method to test new functionalities implemented in OneMap and EmpiricalReads gives a fast and automatically method to select the best software to build linkage maps and answer biological questions for any empirical data.

Output datasets from each main workflow can be easily avaliated in a shiny app called [onemap_workflows_app](). You need to submit your output to the app, and the final page gives the possibility to download the onemap or gusmap object containing the combination of software and paramenters you selected. By now, only one chromosome is avaliated in both workflows, but, downloading the onemap or gusmap object you can repead the map building process in R for other chromosomes without spent all the time needed to compare all the methods. We show a example of these usage in [Quickstart]().


## Shiny app

This shiny app plots analyses datasets (.rds) generated by the errors_workflow. Upload your results in `Upload OneMap workflow results` section. By default, the app shows results from [this study]().

Each icon at the left corner of this page point a different dataset and produce interative plots. Each page plots two graphics than comparisions can be made. Also, you can download de graphics using the button at the end of the page.

## Documentation

Here are some tutorials that better explain how to use the workflows:

* [Introduction](https://cristianetaniguti.github.io/onemap_workflows/introduction.html)
* [Running SimulatedReads workflow](https://cristianetaniguti.github.io/onemap_workflows/simulatedreads.html)
* [Running EmpiricalReads workflow](https://cristianetaniguti.github.io/onemap_workflows/empiricalreads.html)
* [Configurations](https://cristianetaniguti.github.io/onemap_workflows/configuration.html)
* [Usage of sub-workflows](https://cristianetaniguti.github.io/onemap_workflows/subworkflows.html)

You can also have more details about the workflows and how they can be applied:

* [Technical note]()
* [Paper errors]()
* [Paper MNPs]()

## Authors

Cristiane Taniguti is currently a PhD student at ESALQ/USP Statistical Genetics Lab. Access her personal page [here](http://cristianetaniguti.github.io/), and the page of the lab [here](http://augustogarcia.me/statgen-esalq/).
