#' workflow_tasks_times UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_workflow_tasks_times_ui <- function(id){
  ns <- NS(id)
  tagList(
    "Upload the log file generated by the cromwell + WDL workflow. It can be from simulations or empirical. We can upload multiple files.",
    hr(),
    fluidPage(
      box(solidHeader = T,
          tags$h4(tags$b("Upload workflow log file")), br(),
          # Copy the line below to make a file upload manager
          fileInput(ns("wflog"), label = h6("slurm_<depth>.out"), multiple = T),
          #tags$strong("This option is not avaible in this server. Please use:"), br(),
          #tags$code("runGitHub('Cristianetaniguti/Reads2MapApp')")
      ),
      box(solidHeader = T,
          # Copy the line below to make a select box
          selectInput(ns("example_wf"), label = h4(tags$b("Examples")),
                      choices = list("Roses SNP calling" = "roses_snpcalling",
                                     "Roses genotype calling + maps" = "roses_maps",
                                     "Acca SNP calling" = "acca_snpcalling",
                                     "Eucalyptus SNP calling" = "euc_snpcalling"
                      ),
                      selected = "roses_snpcalling"),
      )
    ),
    box(solidHeader = T, collapsible = FALSE, status="primary",
        title = "Time spent by each WDL task",
        width = NULL,
        actionButton(ns("go"), "Update",icon("refresh")),
        # div(downloadButton("wf_out_down"),style="float:right"),
        hr(),
        plotlyOutput(ns("wf_times_out"), width = "100%", height = "100%"),
    )
  )
}

#' workflow_tasks_times Server Functions
#'
#' @noRd 
mod_workflow_tasks_times_server <- function(input, output, session){
  ns <- session$ns
  
  button <- eventReactive(input$go, {
    withProgress(message = 'Building heatmap', value = 0, {
      incProgress(0, detail = paste("Doing part", 1))
      # Empiricals
      ## Roses snpcalling
      if(input$example_wf=="roses_snpcalling"){
        paste(system.file("ext","workflow_times/cromwell_snpcalling_rose_fam2.log", package = "Reads2MapApp"))
        
        # Roses maps
      } else if(input$example_wf=="roses_maps"){
        paste(system.file("ext","workflow_times/maps_rose.log", package = "Reads2MapApp"))
        
        ## Eucalyptus snpcalling
      } else if(input$example_wf=="euc_snpcalling"){
        paste(system.file("ext","workflow_times/cromwell_snpcalling_euc.log", package = "Reads2MapApp"))
        
        ## Acca snpcalling
      } else if(input$example_wf=="acca_snpcalling"){
        paste(system.file("ext","workflow_times/cromwell_snpcalling_acca.log", package = "Reads2MapApp"))
        
      }
    })
  })
  
  output$wf_times_out <- renderPlotly({
    workflow_times(button(), interactive=TRUE)
  })
}

## To be copied in the UI
# mod_workflow_tasks_times_ui("workflow_tasks_times_ui_1")

## To be copied in the server
# mod_workflow_tasks_times_server("workflow_tasks_times_ui_1")
