#' workflow_tasks_times UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_workflow_tasks_times_ui <- function(id){
  ns <- NS(id)
  tagList(
    "Upload the log files generated by the cromwell + WDL workflow and/or slurm. 
    It can be from simulations or empirical. If you don't have your own file, you can check our available examples.",
    hr(),
    fluidPage(
      box(solidHeader = T,
          tags$h4(tags$b("Upload workflow log file")), br(),
          fileInput(ns("wflog"), label = h6("slurm_<depth>.out"), multiple = T),
          tags$h4(tags$b("Upload HPC slurm efficiency file")), br(),
          p("Run the bash script bellow in your HPC `cromwell-executions/<workflow id>` directory"), br(),
          downloadButton(ns("download_script"), "Download"), br(), br(),
          p("Upload the result files `efficiency.infos.txt` and `tasks_id.txt` here"), 
          fileInput(ns("eff1"), label = h6("efficiency.infos.txt"), multiple = F), 
          fileInput(ns("eff2"), label = h6("tasks_id.txt"), multiple = F)
      ),
      box(solidHeader = T,
          # Copy the line below to make a select box
          selectInput(ns("example_wf"), label = h4(tags$b("Examples")),
                      choices = list("Roses SNP calling" = "roses_snpcalling",
                                     "Roses genotype calling + maps" = "roses_maps",
                                     "Acca SNP calling" = "acca_snpcalling",
                                     "Eucalyptus SNP calling" = "euc_snpcalling"
                      ),
                      selected = "roses_snpcalling"),
      )
    ),
    box(solidHeader = T, collapsible = FALSE, status="primary",
        title = "Time spent by each WDL task",
        width = NULL,
        actionButton(ns("go"), "Update",icon("refresh")),
        # div(downloadButton("wf_out_down"),style="float:right"),
        hr(),
        plotlyOutput(ns("wf_times_out"), width = "100%", height = "100%"),
        hr(),
        plotlyOutput(ns("perc"), width = "100%", height = "100%"),
        hr(),
        plotlyOutput(ns("cpu"), width = "100%", height = "100%"),
        hr(),
        plotlyOutput(ns("mem"), width = "100%", height = "100%"),
    )
  )
}

#' workflow_tasks_times Server Functions
#'
#' @noRd 
mod_workflow_tasks_times_server <- function(input, output, session){
  ns <- session$ns
  
  button <- eventReactive(input$go, {
    withProgress(message = 'Building heatmap', value = 0, {
      incProgress(0, detail = paste("Doing part", 1))
      
      if(is.null(input$eff1) & is.null(input$eff2) & is.null(input$wflog)){
        # Empiricals
        ## Roses snpcalling
        if(input$example_wf=="roses_snpcalling"){
          times <- paste(system.file("ext","rose/cromwell_snpcalling_rose_fam2.log", package = "Reads2MapApp"))
          eff <- NULL
          # Roses maps
        } else if(input$example_wf=="roses_maps"){
          times <- system.file("ext","rose/maps_rose.log", package = "Reads2MapApp")
          eff1 <- system.file("ext","rose/efficiency.infos.txt", package = "Reads2MapApp")
          eff2 <- system.file("ext","rose/tasks_id.txt", package = "Reads2MapApp")
          eff <- efficiency_table(infos_seff = eff1, jobs = eff2)
          ## Eucalyptus snpcalling
        } else if(input$example_wf=="euc_snpcalling"){
          times <- system.file("ext","workflow_times/cromwell_snpcalling_euc.log", package = "Reads2MapApp")
          eff1 <- system.file("ext","euc/efficiency.infos.txt", package = "Reads2MapApp")
          eff2 <- system.file("ext","euc/tasks_id.txt", package = "Reads2MapApp")
          eff <- efficiency_table(infos_seff = eff1, jobs = eff2)
          ## Acca snpcalling
        } else if(input$example_wf=="acca_snpcalling"){
          times <- system.file("ext","workflow_times/cromwell_snpcalling_acca.log", package = "Reads2MapApp")
          eff1 <- system.file("ext","acca/efficiency.infos.txt", package = "Reads2MapApp")
          eff2 <- system.file("ext","acca/tasks_id.txt", package = "Reads2MapApp")     
          eff <- efficiency_table(eff1, eff2)
        }
      } else {
        if(!is.null(times))
          times <- input$wflog[,4]
        else times <- NULL
        
        if(!(is.null(input$eff1) | is.null(input$eff1))){
          eff1 <- input$eff1[,4]
          eff2 <- input$eff2[,4]
          eff <- efficiency_table(eff1, eff2)
        } else {
          eff <- NULL
        }
      }
      list(times, eff)
    })
  })
  
  output$wf_times_out <- renderPlotly({
    if(is.null(button()[[1]])) stop("Data not provided")
    workflow_times(button()[[1]], interactive=TRUE)
  })
  
  output$perc <- renderPlotly({
    if(is.null(button()[[2]])) stop("Data not provided")
    efficiency_graphics_perc(eff_table = button()[[2]], interactive=TRUE)
  })  
  
  output$cpu <- renderPlotly({
    if(is.null(button()[[2]])) stop("Data not provided")
    efficiency_graphics_cpu(button()[[2]], interactive=TRUE)
  })  
  
  output$mem <- renderPlotly({
    if(is.null(button()[[2]])) stop("Data not provided")
    efficiency_graphics_mem(button()[[2]], interactive=TRUE)
  })  
  
  output$download_script <- downloadHandler(
    filename = function() {
      paste0("efficiency.sh")
    },
    content = function(file) {
      file <- system.file("ext/efficiency_script.sh", package = "Reads2MapApp")
    }
  )
}

## To be copied in the UI
# mod_workflow_tasks_times_ui("workflow_tasks_times_ui_1")

## To be copied in the server
# mod_workflow_tasks_times_server("workflow_tasks_times_ui_1")
