#' workflow_tasks_times UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_workflow_tasks_times_ui <- function(id){
  ns <- NS(id)
  tagList(
    "Upload the log file generated by the cromwell + WDL workflow. It can be from simulations or empirical. We can upload multiple files.",
    hr(),
    fluidPage(
      box(solidHeader = T,
          tags$h4(tags$b("Upload workflow log file")), br(),
          # Copy the line below to make a file upload manager
          fileInput(ns("wflog"), label = h6("slurm_<depth>.out"), multiple = T),
          #tags$strong("This option is not avaible in this server. Please use:"), br(),
          #tags$code("runGitHub('Cristianetaniguti/Reads2MapApp')")
      ),
      box(solidHeader = T,
          # Copy the line below to make a select box
          selectInput(ns("example_wf"), label = h4(tags$b("Examples")),
                      choices = list("P.tremula empirical SNP calling" = "populus_snpcalling",
                                     "P.tremula empirical maps with contaminant" = "populus_emp_cont",
                                     "P.tremula empirical maps without contaminant" = "populus_emp",
                                     "Eucalyptus empirical SNP calling" = "eucalyptus_snpcalling",
                                     "Eucalyptus empirical maps" = "eucalyptus_map",
                                     "P. tremula simulation 37cM of chromosome 10 -  5 families pop size 200 depth 20" = "populus_simu_5fam_pop200_depth20"
                      ),
                      selected = "populus_emp"),
      )
    ),
    box(solidHeader = T, collapsible = FALSE, status="primary",
        title = "Time spent by each WDL task",
        width = NULL,
        actionButton(ns("go"), "Update",icon("refresh")),
        # div(downloadButton("wf_out_down"),style="float:right"),
        hr(),
        plotlyOutput(ns("wf_times_out"), width = "100%", height = "100%"),
    )
  )
}

#' workflow_tasks_times Server Functions
#'
#' @noRd 
mod_workflow_tasks_times_server <- function(input, output, session){
  ns <- session$ns
  
  button <- eventReactive(input$go, {
    withProgress(message = 'Building heatmap', value = 0, {
      incProgress(0, detail = paste("Doing part", 1))
      # Empiricals
      ## Populus snpcalling
      if(input$example_wf=="populus_snpcalling"){
        paste(system.file("ext","populus/biallelics/slurm-67440032_snpcalling_popu.out", package = "Reads2MapApp"))
        
        ## Populus maps
      } else if(input$example_wf=="populus_emp_cont"){
        paste(system.file("ext","populus/biallelics/with_contaminants/maps_emp_populus.log", package = "Reads2MapApp"))
      } else if(input$example_wf=="populus_emp"){
        paste(system.file("ext","populus/biallelics/without_contaminants/populus_rmind.log", package = "Reads2MapApp"))
        
        ## Eucalyptus snpcalling
      } else if(input$example_wf=="eucalyptus_snpcalling"){
        paste(system.file("ext","eucalyptus/biallelics/slurm-67472436_snpcalling_euc.out", package = "Reads2MapApp"))
        
        ## Eucalyptus maps
      } else if(input$example_wf=="eucalyptus_map"){
        paste(system.file("ext","eucalyptus/biallelics/euc.log", package = "Reads2MapApp"))
        
        # Simulations
      } else if(input$example_wf=="populus_simu_5fam_pop200_depth20"){
        paste(system.file("ext","simulations/RADinitio37/biallelics/SimulatedReads.bi.200.20.log", package = "Reads2MapApp"))
      }
    })
  })
  
  output$wf_times_out <- renderPlotly({
    workflow_times(button(), interactive=TRUE)
  })
}

## To be copied in the UI
# mod_workflow_tasks_times_ui("workflow_tasks_times_ui_1")

## To be copied in the server
# mod_workflow_tasks_times_server("workflow_tasks_times_ui_1")
